name: number_to_text_spanish
description: "Convierte números del 1 al 99999 en su representación textual en español"
version: 1.1.1
homepage: https://github.com/XXcartmineX/number_to_text_spanish

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
